### PR TITLE
Add string case-insensitive filter

### PR DESCRIPTION
**Pull request by houcros**

### CODE REVIEW

**Comment by simao** [comment]
This seems rather specific.. why do you need it libats?

Can you write a test for it? There should be some tests for db stuff in this module already.

**Comment by houcros** [comment]
Yeah, we don't _actually_ need it here, but I thought it might come in handy since we already have the `maybeContains` method. I'm fine closing this and using it where needed if you see no real advantage in having it here.

**Comment by simao** [comment]
Lets keep it where it's needed and move it here if we need it more projects.

**Comment by houcros** [comment]
👍

**Pull request closed without merging**
