### PR TITLE
Use ResultCode in InstallationResult for type safety

### PR DESCRIPTION
**Pull request by houcros**
Let's use this `ResultCode` and `ResultDescription` value classes in the `InstallationResult` to gain some type safety and readability? See #97.

### CODE REVIEW

**Comment by nkly** [comment]
Sounds good to me :+1: Do you plan to refactor dependent services soon?

**Comment by houcros** [comment]
Yes, I already started to refactor campaigner. Device registry would be next.

**Comment by houcros** [comment]
I added `ResultDescription` here as well.

**Comment by houcros** [comment]
@jerry Do you see any reason to not merge this yet? Maybe it would impede the changes you're doing in director? If that's not the case I would like to merge this tomorrow.

**Pull request merged**
