### PR TITLE
Use finagle 18.2.0

### PR DESCRIPTION
**Pull request by koshelev**

### CODE REVIEW

**Comment by koshelev** [comment]
@simao not sure what you mean. netty 4.1.x is current netty version, and it is what we are using.

**Comment by simao** [comment]
Sorry I meant netty 3.x, I though finagle pulled netty 3.x and not 4.x though, there was an eric-security-ticket pending for that reason.

**Comment by koshelev** [comment]
Oh, I see. IT should pull both. There are still some compile-time dependencies on netty3, will have to look at exclusion rules. At runtime we are using only netty4 to serve requests, so it should be ok.

**Comment by simao** [comment]
ok. here is the issue: https://advancedtelematic.atlassian.net/browse/PRO-4436

**Comment by koshelev** [comment]
Ok, I will take care of it

**Pull request merged**
